language: python
python:
- "2.7"
# command to let run a real GUI application or web browser
install: "pip install -r requirements.txt"
#before_script:
#- "flake8 --ignore= manage.py sched tests/features"
# command to run tests
script:
- coverage run --omit="*site-packages*" testsUnit.py
- coverage report -m
- nosetests --with-doctest -s sched
- python manage.py runserver & lettuce tests